regressiondata <- read.csv("regressiondata.csv")
regressiondata$youth.perc <- (regressiondata$youth/regressiondata$population.2016)*100 
regressiondata$male.youth <- NULL
regressiondata$youth <- NULL
regressiondata$male.above.15 <- NULL
regressiondata$female.above.15 <- NULL
regressiondata$lone.parent.families <- NULL
regressiondata$lone.parent.families.perc <- regressiondata$lone.parent.families.perc*100
regressiondata$low.income <- NULL
regressiondata$middle.income <- NULL
regressiondata$high.income <- NULL
regressiondata$people.ei <- NULL
regressiondata$people.ei.per <- NULL
regressiondata$median.income <- NULL
regressiondata$no.hholds.bottom.20per <- NULL
regressiondata$hholds.bottom.20per.per <- NULL
regressiondata$low.income.pop <- NULL
regressiondata$low.income.pop.18.to.64 <- NULL
regressiondata$low.income.pop.perc.18.to.64 <- NULL
regressiondata$non.citizens <- NULL
regressiondata$non.citizens.perc <- regressiondata$non.citizens.perc*100
regressiondata$immigrants <- NULL
regressiondata$immigrants.perc <- NULL
regressiondata$immigrants.recent <- NULL
regressiondata$immigrants.recent.perc <- regressiondata$immigrants.recent.perc*100
regressiondata$refugees <- NULL
regressiondata$refugees.perc <- regressiondata$refugees.perc*100
regressiondata$vis.minorities <- NULL
regressiondata$vis.minorities.perc <- regressiondata$vis.minorities.perc*100
regressiondata$renters <- NULL
regressiondata$renters.perc <- regressiondata$renters.perc*100
regressiondata$houses <- NULL
regressiondata$houses.perc <- regressiondata$houses.perc*100
regressiondata$unsuitable.housing <- NULL
regressiondata$unsuitable.housing.perc <- NULL
regressiondata$hhlds.mjr.rprs <- NULL
regressiondata$hhlds.mjr.rprs.perc <- NULL
regressiondata$unaffordable.housing <- NULL
regressiondata$unaffordale.housing.perc <- NULL
regressiondata$less.than.high.school <- NULL
regressiondata$less.than.high.school.perc <- regressiondata$less.than.high.school.perc*100
regressiondata$high.school.cert <- NULL
regressiondata$high.school.cert.perc <- regressiondata$high.school.cert*100
regressiondata$post.sec.or.above <- NULL
regressiondata$post.sec.or.above.perc <- regressiondata$post.sec.or.above.perc*100
regressiondata$unemployed <- NULL
regressiondata$unemployed.males <- NULL
regressiondata$unemployment.rate.males <- NULL

regressiondata <- round(regressiondata, digits = 3)

write.csv(regressiondata, "regressiondata.csv", row.names=FALSE)
